---
- name: Встановити WildFly 31.0.1 Final
  hosts: all
  become: true
  tasks:
    # - name: Встановити необхідні залежності
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - gtar
    #     - xmlstarlet
          # - gtar

    # - name: Update repositories cache
    #   ansible.builtin.apt:
    #     update_cache: yes

    # - name: Install jdk-11
    #   ansible.builtin.apt:
    #     name: openjdk-11-jdk
    #     state: present

    - name: Завантажити WildFly 31.0.1 Final
      get_url:
        url: "https://github.com/wildfly/wildfly/releases/download/31.0.1.Final/wildfly-31.0.1.Final.tar.gz"
        dest: "/tmp/wildfly-31.0.1.Final.tar.gz"
        mode: '0644'

    - name: Розпакувати WildFly
      unarchive:
        src: "/tmp/wildfly-31.0.1.Final.tar.gz"
        dest: "/opt"
        remote_src: true
        creates: "/opt/wildfly-31.0.1.Final"

    - name: Створити символічне посилання для WildFly
      file:
        src: "/opt/wildfly-31.0.1.Final"
        dest: "/opt/wildfly"
        state: link
   
    - name: Створити групу wildfly, якщо вона не існує
      ansible.builtin.group:
        name: wildfly
        state: present

    - name: Додати системного користувача без домашньої директорії
      ansible.builtin.user:
        name: wildfly
        system: true
        createhome: false
        group: wildfly
          
    - name: Змінити власника директорії /opt/wildfly
      ansible.builtin.file:
        path: /opt/wildfly-31.0.1.Final
        owner: wildfly
        group: wildfly
        recurse: true

    - name: Copy configuration to WildFly
      ansible.builtin.copy:
        src: ./files/wildfly.service
        dest: /etc/systemd/system/wildfly.service

    - name: Перезавантажити systemd
      systemd:
        daemon_reload: true

    - name: Включити та запустити WildFly
      service:
        name: wildfly
        enabled: true
        state: started

    - name: Перезапустити сервіс apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted

    - name: Перезапустити сервіс wildfly
      ansible.builtin.systemd:
        name: apache2
        state: restarted
